
[database]
  hostname = "localhost"
  password = "${http_proxy}"
  port = 5432
  username = "postgres"

[output]

  [output.file]

    [output.file.path]
      folder = "Temp"
      fullpath = "D:\\Temp"
